version: "3.8"

services:
  app:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/backend
      - PORT=3000
      - HOST=0.0.0.0
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
