name: Run Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Test Environment
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build images with no cache
      - name: Build base image
        run: |
          docker build --no-cache \
            --build-arg BUILDTIME=${{ github.sha }} \
            -f Dockerfile \
            -t 288792505174.dkr.ecr.us-east-1.amazonaws.com/test:latest .

      - name: Login ECR Repository
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 288792505174.dkr.ecr.us-east-1.amazonaws.com

      # Push images
      - name: Push images to ECR
        run: |
          docker push 288792505174.dkr.ecr.us-east-1.amazonaws.com/test:latest
